// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenLineOps.Operations.Infra.Data.Persistence;

#nullable disable

namespace OpenLineOps.Operations.Infra.Data.Persistence.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20260630102846_InitialOperationsSqlite")]
    partial class InitialOperationsSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OpenLineOps.Operations.Domain.Aggregates.Alarm", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcknowledgedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("RaisedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaisedAtUtc");

                    b.HasIndex("StationId", "Status");

                    b.ToTable("operations_alarms", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
