<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\OpenLineOps.Application.Abstractions\OpenLineOps.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\modules\OpenLineOps.Commissioning.Application\OpenLineOps.Commissioning.Application.csproj" />
    <ProjectReference Include="..\..\modules\OpenLineOps.Commissioning.Domain\OpenLineOps.Commissioning.Domain.csproj" />
    <ProjectReference Include="..\..\modules\OpenLineOps.Commissioning.Infrastructure\OpenLineOps.Commissioning.Infrastructure.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
