<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../shared/OpenLineOps.Application.Abstractions/OpenLineOps.Application.Abstractions.csproj" />
    <ProjectReference Include="../OpenLineOps.Recipes.Domain/OpenLineOps.Recipes.Domain.csproj" />
  </ItemGroup>

</Project>
