namespace OpenLineOps.Traceability.Application.Records;

public sealed record TraceRecordDetails(
    Guid TraceRecordId,
    Guid ProductionRunId,
    string ProjectId,
    string ApplicationId,
    string ProjectSnapshotId,
    string TopologyId,
    string ProductionLineDefinitionId,
    string DutModelId,
    string DutIdentityInputKey,
    string DutIdentityValue,
    string? BatchId,
    string? FixtureId,
    string? DeviceId,
    string ActorId,
    string RunStatus,
    string Judgement,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset CompletedAtUtc,
    string? FailureCode,
    string? FailureReason,
    IReadOnlyCollection<TraceStageExecutionDetails> Stages,
    IReadOnlyCollection<AuditEntryDetails> AuditEntries);

public sealed record TraceRecordSummary(
    Guid TraceRecordId,
    Guid ProductionRunId,
    string ProjectId,
    string ApplicationId,
    string ProjectSnapshotId,
    string TopologyId,
    string ProductionLineDefinitionId,
    string DutModelId,
    string DutIdentityInputKey,
    string DutIdentityValue,
    string? BatchId,
    string? FixtureId,
    string? DeviceId,
    string ActorId,
    string RunStatus,
    string Judgement,
    DateTimeOffset CompletedAtUtc,
    int StageCount,
    int FailedStageCount,
    int CommandCount,
    int MeasurementCount,
    int ArtifactCount,
    int IncidentCount);

public sealed record TraceStageExecutionDetails(
    string StageId,
    int Sequence,
    string WorkstationId,
    string StationId,
    string ProcessDefinitionId,
    string ProcessVersionId,
    string ConfigurationSnapshotId,
    string RecipeSnapshotId,
    Guid? RuntimeSessionId,
    string? RuntimeSessionStatus,
    string Status,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset CompletedAtUtc,
    string? FailureCode,
    string? FailureReason,
    int CompletedStepCount,
    int CommandCount,
    int IncidentCount,
    IReadOnlyCollection<TraceCommandDetails> Commands,
    IReadOnlyCollection<MeasurementRecordDetails> Measurements,
    IReadOnlyCollection<ArtifactRecordDetails> Artifacts,
    IReadOnlyCollection<TraceIncidentDetails> Incidents);

public sealed record TraceCommandDetails(
    Guid RuntimeCommandId,
    Guid RuntimeStepId,
    string ActionId,
    string TargetKind,
    string TargetId,
    string TargetCapabilityId,
    string CommandName,
    string Status,
    string? SemanticOutcome,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset DeadlineAtUtc,
    DateTimeOffset? AcceptedAtUtc,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset? CompletedAtUtc,
    string? ResultPayload,
    string? FailureReason);

public sealed record MeasurementRecordDetails(
    Guid MeasurementRecordId,
    string Name,
    decimal? NumericValue,
    string? TextValue,
    string? Unit,
    string? DeviceId,
    Guid? RuntimeCommandId,
    string ActionId,
    string TargetKind,
    string TargetId,
    string CommandStatus,
    bool? Passed,
    DateTimeOffset MeasuredAtUtc);

public sealed record ArtifactRecordDetails(
    Guid ArtifactRecordId,
    string Name,
    string Kind,
    string StorageKey,
    string? MediaType,
    long SizeBytes,
    string? Sha256,
    string? DeviceId,
    DateTimeOffset CapturedAtUtc);

public sealed record TraceIncidentDetails(
    Guid RuntimeIncidentId,
    string Severity,
    string Code,
    string Message,
    DateTimeOffset OccurredAtUtc);

public sealed record AuditEntryDetails(
    Guid AuditEntryId,
    string ActorId,
    string Action,
    string? Detail,
    DateTimeOffset OccurredAtUtc);
