// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenLineOps.Devices.Infrastructure.Persistence.Ef;

#nullable disable

namespace OpenLineOps.Devices.Infrastructure.Persistence.Ef.Migrations
{
    [DbContext(typeof(DevicesDbContext))]
    partial class DevicesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OpenLineOps.Devices.Domain.Definitions.DeviceDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.ToTable("device_definitions_ef", (string)null);
                });

            modelBuilder.Entity("OpenLineOps.Devices.Domain.Instances.DeviceInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConnectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaultReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastDisconnectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("DefinitionId", "Status");

                    b.ToTable("device_instances_ef", (string)null);
                });

            modelBuilder.Entity("OpenLineOps.Devices.Domain.Definitions.DeviceDefinition", b =>
                {
                    b.OwnsMany("OpenLineOps.Devices.Domain.Definitions.DeviceCapability", "Capabilities", b1 =>
                        {
                            b1.Property<string>("DefinitionId")
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .HasMaxLength(160)
                                .HasColumnType("TEXT")
                                .HasColumnName("capability_id");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.HasKey("DefinitionId", "Id");

                            b1.ToTable("device_definition_capabilities_ef", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DefinitionId");
                        });

                    b.OwnsMany("OpenLineOps.Devices.Domain.Definitions.DeviceCommandDefinition", "Commands", b1 =>
                        {
                            b1.Property<string>("DefinitionId")
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .HasMaxLength(180)
                                .HasColumnType("TEXT")
                                .HasColumnName("command_definition_id");

                            b1.Property<string>("CapabilityId")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("TEXT")
                                .HasColumnName("capability_id");

                            b1.Property<string>("CommandName")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("TEXT");

                            b1.Property<string>("InputSchema")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxRetries")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("OutputSchema")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("Timeout")
                                .HasColumnType("TEXT");

                            b1.HasKey("DefinitionId", "Id");

                            b1.ToTable("device_definition_commands_ef", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DefinitionId");
                        });

                    b.Navigation("Capabilities");

                    b.Navigation("Commands");
                });

            modelBuilder.Entity("OpenLineOps.Devices.Domain.Instances.DeviceInstance", b =>
                {
                    b.OwnsOne("OpenLineOps.Devices.Domain.Instances.DeviceEndpoint", "Endpoint", b1 =>
                        {
                            b1.Property<string>("DeviceInstanceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("endpoint_address");

                            b1.Property<string>("Protocol")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT")
                                .HasColumnName("endpoint_protocol");

                            b1.HasKey("DeviceInstanceId");

                            b1.ToTable("device_instances_ef");

                            b1.WithOwner()
                                .HasForeignKey("DeviceInstanceId");
                        });

                    b.Navigation("Endpoint")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
