namespace OpenLineOps.Runtime.Api.Models;

public sealed record ProductionRunResponse(
    Guid ProductionRunId,
    string ProjectId,
    string ApplicationId,
    string ProjectSnapshotId,
    string TopologyId,
    string ProductionLineDefinitionId,
    RuntimeDutIdentityResponse DutIdentity,
    string? BatchId,
    string? FixtureId,
    string? DeviceId,
    string ActorId,
    string Status,
    bool IsTerminal,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset LastTransitionAtUtc,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset? CompletedAtUtc,
    string? FailureCode,
    string? FailureReason,
    int CompletedStageCount,
    int CompletedStepCount,
    int CommandCount,
    int IncidentCount,
    IReadOnlyCollection<ProductionRunStageResponse> Stages);

public sealed record ProductionRunStageResponse(
    string StageId,
    int Sequence,
    string WorkstationId,
    string StationSystemId,
    string ProcessDefinitionId,
    string ProcessVersionId,
    string ConfigurationSnapshotId,
    string RecipeSnapshotId,
    string Status,
    bool IsTerminal,
    Guid? RuntimeSessionId,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset? CompletedAtUtc,
    string? FailureCode,
    string? FailureReason,
    int CompletedStepCount,
    int CommandCount,
    int IncidentCount);
