namespace OpenLineOps.Runtime.Api.Models;

public sealed record RuntimeTimelineEntryResponse(
    long Sequence,
    Guid EventId,
    DateTimeOffset OccurredAtUtc,
    string EventName,
    Guid SessionId,
    string ProjectId,
    string ApplicationId,
    string ProjectSnapshotId,
    string TopologyId,
    Guid ProductionRunId,
    string ProductionLineDefinitionId,
    string StageId,
    int StageSequence,
    string WorkstationId,
    RuntimeDutIdentityResponse DutIdentity,
    string StationSystemId,
    string EntityKind,
    string? EntityId,
    string? FromStatus,
    string? ToStatus,
    string? Reason,
    string? Severity,
    string? Code,
    string SessionStatus);
