namespace OpenLineOps.Runtime.Api.Models;

public sealed record RuntimeTimelineEntryResponse(
    long Sequence,
    Guid EventId,
    DateTimeOffset OccurredAtUtc,
    string EventName,
    Guid SessionId,
    string ProjectId,
    string ApplicationId,
    string ProjectSnapshotId,
    string TopologyId,
    Guid ProductionRunId,
    string ProductionLineDefinitionId,
    string OperationId,
    int OperationAttempt,
    string StationSystemId,
    RuntimeProductionUnitIdentityResponse ProductionUnitIdentity,
    string RuntimeStationId,
    string EntityKind,
    string? EntityId,
    string? FromStatus,
    string? ToStatus,
    string? Reason,
    string? Severity,
    string? Code,
    string SessionStatus);
