<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../OpenLineOps.Maintenance.Application/OpenLineOps.Maintenance.Application.csproj" />
    <ProjectReference Include="../OpenLineOps.Maintenance.Domain/OpenLineOps.Maintenance.Domain.csproj" />
  </ItemGroup>

</Project>
